### PR TITLE
Add support for require, dynamic import statements, decouple tree state from parser

### PR DESCRIPTION
**Pull request by MajorLift**
See: Issue #7

# Features

### a) Newly supports a subset of `require()` syntax

  - DOES support object destructuring with alias assignment
    - e.g. ```const { foo: alias, bar } = require("./module")```
  - DOES support array destructuring
    - e.g. ```const [foo, bar] = require("./module")```
  - DOES NOT support namespaces and member expressions
    - e.g. ```const foo = require("./module"); ... ; <foo.component />;```
  - DOES NOT support invocations or method/member calls
    - e.g. ```const foo = require("./module")();```
    - e.g. ```const foo = require("./module").method(arg);```
    
### b) Newly supports a subset of variable declaration imports 

  - DOES support object destructuring with alias assignment, and array destructuring 
    (no actual use cases, but intermediate step towards fully supporting dynamic imports)
    - e.g. ```const { foo: alias, bar } = import("./module")```
    - e.g. ```const [foo, bar] = import("./module")```
  - DOES NOT support await expressions, .then() chains, or Promise.resolve() calls for dynamic imports
    - e.g. ```const foo = await import("./module")```
    - e.g. ```import("./module").then(mod => mod.loadPage())```
    - e.g. ```const foo = Promise.resolve(import("./module"))``` 

### c) Introduces Babel type guards-based parsing strategy
  - Partially replaces obsolete `Babylon` token-based parsing.
  - Allows for more declarative, extensible code, including the above feature updates.
  - Enables explicit checks with strong typing for all control flow branches.

### d) Converts `SaplingParser` into a static class

- `.parse()` is the only public (and static) method. 
- Grouped methods into objects (`ParserHelpers`, `ASTParser`, `ImportParser`, `ExportParser`).
- Converted all `SaplingParser` methods to pure functions where possible, and provided clear indication of mutations.
  - `.parser()` relies entirely on mutating input data in-place, but this was previously unclear due to its non-void return type. 
- Redundant `parser` and `tree` instance usage consolidated in `SidebarProvider` and `parser.test`

- There is no conceptual benefit to modeling `SaplingParser` as an object that can have multiple instances, as there is no variation in parsing functionality between instances, and the only state it encapsulates is tree-related. 
  - Enabling the parser to support different configurations or multiple interfaces would be a good use case for converting it to a factory or strategy class in the future.

### Encapsulated Tree state and methods to new class.

- Strong low-cohesion indicator: No reference to `this.tree` in any `SaplingParser` class method that doesn't have `Tree` in its name.
- Supporting multiple Tree object instances is a more useful abstraction. 
- Migrated `.toggleNode()`, `.updateTree()`, `.#traverseTree()` from `SaplingParser` to `SaplingTree`.
- Nested nodes are accessible with `.get()` as follows (useful in parser test file): 
e.g. `tree.get(0, 1, 2)` is equivalent to `tree.children[0].children[1].children[2]`.
- Tree class objects are serializable/deserializable for messaging as `workspaceState` `Memento` object.

# Test Status

- Features supported by latest version fully functional.
- Added test cases for new features.

Screenshot 2023-02-11 at 9 20 37 PM

# Issues

- Mocha test suite not functional due to typescript module resolution issue in emitted code. 
  - Manually editing `types` directory path in `extension/out/SaplingParser.js` temporarily resolves issue.
- Remove `SaplingTree` from `types` barrel file. 
- General bug fixing, refactoring, consistent styling, removing dead code paths and obsolete comments and tests. 

# Roadmap

- Clean up Tree and Node types for interfacing with parser vs. webview, as well as a serialized type for messaging between the two. Each require slightly different set of properties. 
- Expand import and export statement support. 
  - Add support for barrel files. 
- Rewrite `SaplingParser` `.getJSXChildren()`, `.getJSXProps()`, `.checkForRedux()` methods to use Babel type guards. 
  - Add support for Redux hooks.

### CODE REVIEW

**Comment by hb1998** [comment]
@MajorLift  Il convert the pr to a draft? since u have mentioned you have some Todos pending.

**Comment by hb1998** [comment]
@MajorLift  
I have created a new branch 
https://github.com/hb1998/react-component-tree/tree/parser/babel-type-guards

Moving forward you can send PRs to that branch, we can test the branch internally and release, once it's stable.

**Comment by MajorLift** [comment]
@hb1998 Done! The PR is fully functional and can be merged as is. The mocha test issue is the only thing that needs fixing. I'll take another look at it with fresh eyes tomorrow just to be sure.

**Comment by hb1998** [comment]
> @hb1998 Done! The PR is fully functional and can be merged as is. The mocha test issue is the only thing that needs fixing. I'll take another look at it with fresh eyes tomorrow just to be sure.

@MajorLift  sure will test it meanwhile. 
Thanks for the contribution.

**Pull request merged**
