### PR TITLE
docs(readme): extensive edits, updates

### PR DESCRIPTION
**Pull request by MajorLift**
## Readme updates

- See: #15
- Preview: https://github.com/MajorLift/react-component-tree/blob/readme/update-v1.1.0/extension/README.md
  - Edit: **Restored screen captures!**
- Feel free to add edits of your own, or provide feedback/suggestions on any of these changes. 
---
- New tagline
- Consistent emphasis, capitalization for product name.
- New badges for package, repo stats. 
- New badges for "built with" section.
---
- Updated "getting started" section to match current feature set.
- General editing/rewriting with focus on concise, marketable keywords, phrasing, calls to action.
---
- Updated bug report, feature request links to corresponding issue templates.
- ~~Removed obsolete screenshots.~~
- Cleaned up styling based on markdown linter warnings.
- Deleted obsolete readme file in root dir.

## Other

- Set up github actions ci/cd workflows.
  - Parser test suite runs for commits, PRs on all branches.
  - Full test suite runs only for PRs into master branch.
    - Extension tests need to be fixed. 
    - TODO: writing webview tests with react-testing-library?

- Fixed dark mode background color being inconsistent with other extensions.

**Before:**
Screenshot 2023-02-13 at 8 10 14 PM
**After:**
Screenshot 2023-02-13 at 8 09 41 PM

### CODE REVIEW

**Comment by hb1998** [comment]
@MajorLift  I haven't gone through the PR yet, little held up with my full time, will merge it over the weekend.

**Comment by MajorLift** [comment]
@hb1998 No worries, take your time. :)

**Comment by hb1998** [comment]
@MajorLift 
- I see the readme in the root of the project is removed, github won't show the readme then, right? why remove it ?. 
- > React Component Tree logo from [Freepik](https://www.freepik.com/vectors/tree)

   Actually, I made the logo   😅 
- Apart from that things are looking good

**Comment by MajorLift** [comment]
@hb1998 Updated!

**Pull request merged**
